### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by jxiaoalex** [infeng/react-viewer-mobile#3]
Hello, it can't be installed. How can we solve it?

**Comment by infeng** [comment]
Can you provide the error screenshot?

**Comment by jxiaoalex** [comment]
现在install了，好像不支持react 16+
![image](https://user-images.githubusercontent.com/35950895/58221103-eaf95380-7d43-11e9-857a-f1e7d4d72749.png)

**Comment by infeng** [comment]
这个是因为你按照了多个版本的 ` react` 吧

**Comment by jxiaoalex** [comment]
只用了react 16.2呢

**Comment by infeng** [comment]
刚更新了一版，之前的依赖模式错了，把 `node_modules` 删除重新安装试下

**Comment by jxiaoalex** [comment]
![image](https://user-images.githubusercontent.com/35950895/58222441-a1f7ce00-7d48-11e9-94a6-e0b37a85be04.png)
重试了，安装不到任何东西呢

**Comment by infeng** [comment]
`package-lock.json` 也要删除

**Comment by jxiaoalex** [comment]
![image](https://user-images.githubusercontent.com/35950895/58222939-58a87e00-7d4a-11e9-9e1a-5bfab2e0901a.png)
package.json, package-lock.json, node_modules 都删除了呢，还是装不到

**Comment by infeng** [comment]
再试下吧，刚刚更新没有构建

**Comment by jxiaoalex** [comment]
可以了，谢谢，还不支持旋转吧？

**Comment by infeng** [comment]
暂不支持，这个项目没有继续迭代了，建议你找另一个
